# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_times --refiner-path refiner/saved/  --refiner-name times_nll_0.25 --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_times --refiner-path refiner/saved/  --refiner-name times_nll_0.25 --on-test --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_bradly --refiner-path refiner/saved/  --refiner-name bradly_nll_0.35 --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_bradly --refiner-path refiner/saved/  --refiner-name bradly_nll_0.35 --on-test --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_brush --refiner-path refiner/saved/  --refiner-name brush_nll_0.40 --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_brush --refiner-path refiner/saved/  --refiner-name brush_nll_0.40 --on-test --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_hannotate --refiner-path refiner/saved/  --refiner-name hannotate_nll_0.15 --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_hannotate --refiner-path refiner/saved/  --refiner-name hannotate_nll_0.15 --on-test --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.25 --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.25 --on-test --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_mixall --refiner-path refiner/saved/  --refiner-name mixall_nll_0.25 --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 410 --classifier-path classifier/saved/  --classifier-name ideal_mixall --refiner-path refiner/saved/  --refiner-name mixall_nll_0.25 --on-test --verbose

# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_mixall --refiner-path refiner/saved/  --refiner-name mixall_nll_0.55_whole --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_mixall --refiner-path refiner/saved/  --refiner-name mixall_nll_0.55_whole --on-test --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_times --refiner-path refiner/saved/  --refiner-name times_nll_0.55_whole --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_times --refiner-path refiner/saved/  --refiner-name times_nll_0.55_whole --on-test --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_bradly --refiner-path refiner/saved/  --refiner-name bradly_nll_0.55_whole --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_bradly --refiner-path refiner/saved/  --refiner-name bradly_nll_0.55_whole --on-test --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_brush --refiner-path refiner/saved/  --refiner-name brush_nll_0.55_whole --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_brush --refiner-path refiner/saved/  --refiner-name brush_nll_0.55_whole --on-test --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_hannotate --refiner-path refiner/saved/  --refiner-name hannotate_nll_0.55_whole --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_hannotate --refiner-path refiner/saved/  --refiner-name hannotate_nll_0.55_whole --on-test --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.55_whole --verbose
# python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.55_whole --on-test --verbose


python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.56_whole --verbose
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.56_whole --on-test --verbose
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.57_whole --verbose
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.57_whole --on-test --verbose
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.58_whole --verbose
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.58_whole --on-test --verbose
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.59_whole --verbose
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.59_whole --on-test --verbose
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.60_whole --verbose
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 10000 --classifier-path classifier/saved/  --classifier-name ideal_typewriter --refiner-path refiner/saved/  --refiner-name typewriter_nll_0.60_whole --on-test --verbose
