python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.00
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.00 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.05
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.05 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.10
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.10 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.15
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.15 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.20
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.20 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.25
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.25 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.30
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.30 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.35
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.35 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.40
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.40 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.45
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.45 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.50
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.50 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.55
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.55 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.60
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.60 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.65
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.65 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.70
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.70 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.75
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.75 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.85
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.85 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.90
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.90 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.95
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd0.95 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd1.00
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 200 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name mnist_unet_lmd1.00 --on-test
