python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.00
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.00 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.05
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.05 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.10
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.10 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.15
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.15 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.20
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.20 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.25
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.25 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.30
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.30 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.35
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.35 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.40
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.40 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.45
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.45 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.50
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.50 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.55
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.55 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.60
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.60 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.65
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.65 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.70
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.70 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.75
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.75 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.80
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.80 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.85
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.85 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.90
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.90 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.95
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_0.95 --on-test
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_1.00
python test/test_refiner.py --batch-size 64 --test-batch 64 --test-size 900 --classifier-path classifier/saved/  --classifier-name mnist_lenet --refiner-path refiner/saved/  --refiner-name nll_1.00 --on-test
