# delta = fearture_l1, eta = nll, mixall
# python refine_apprentice.py --refiner unet --lbd 0.00 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.00
# python refine_apprentice.py --refiner unet --lbd 0.05 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.05
# python refine_apprentice.py --refiner unet --lbd 0.10 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.10
# python refine_apprentice.py --refiner unet --lbd 0.15 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.15
# python refine_apprentice.py --refiner unet --lbd 0.20 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.20
# python refine_apprentice.py --refiner unet --lbd 0.25 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.25_whole
# python refine_apprentice.py --refiner unet --lbd 0.30 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.30
# python refine_apprentice.py --refiner unet --lbd 0.35 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.35
# python refine_apprentice.py --refiner unet --lbd 0.40 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.40
# python refine_apprentice.py --refiner unet --lbd 0.45 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.45
# python refine_apprentice.py --refiner unet --lbd 0.50 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.50
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.55
# python refine_apprentice.py --refiner unet --lbd 0.60 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.60
# python refine_apprentice.py --refiner unet --lbd 0.65 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.65
# python refine_apprentice.py --refiner unet --lbd 0.70 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.70
# python refine_apprentice.py --refiner unet --lbd 0.75 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.75
# python refine_apprentice.py --refiner unet --lbd 0.85 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.80
# python refine_apprentice.py --refiner unet --lbd 0.85 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.85
# python refine_apprentice.py --refiner unet --lbd 0.90 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.90
# python refine_apprentice.py --refiner unet --lbd 0.95 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.95
# python refine_apprentice.py --refiner unet --lbd 1.00 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 9795 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_1.00


# python refine_apprentice.py --refiner unet --lbd 0.56 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.56_whole
# python refine_apprentice.py --refiner unet --lbd 0.57 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.57_whole
# python refine_apprentice.py --refiner unet --lbd 0.58 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.58_whole
# python refine_apprentice.py --refiner unet --lbd 0.59 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.59_whole
# python refine_apprentice.py --refiner unet --lbd 0.60 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.60_whole

# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 500 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size   100 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.55_100
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 300 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size   200 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.55_200
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 200 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size   500 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.55_500
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 100 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size  1000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.55_1000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 50 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size  2000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.55_2000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 30 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size  5000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.55_5000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 20 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size 10000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.55_10000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 15 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size 20000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.55_20000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size 50000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_typewriter --save refiner/saved/ --log refiner/logs/ --name typewriter_nll_0.55_50000


# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 500 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size   100 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_times --save refiner/saved/ --log refiner/logs/ --name times_nll_0.55_100
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 300 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size   200 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_times --save refiner/saved/ --log refiner/logs/ --name times_nll_0.55_200
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 200 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size   500 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_times --save refiner/saved/ --log refiner/logs/ --name times_nll_0.55_500
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 100 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size  1000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_times --save refiner/saved/ --log refiner/logs/ --name times_nll_0.55_1000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 50 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size  2000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_times --save refiner/saved/ --log refiner/logs/ --name times_nll_0.55_2000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 30 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size  5000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_times --save refiner/saved/ --log refiner/logs/ --name times_nll_0.55_5000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 20 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size 10000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_times --save refiner/saved/ --log refiner/logs/ --name times_nll_0.55_10000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 15 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size 20000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_times --save refiner/saved/ --log refiner/logs/ --name times_nll_0.55_20000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size 50000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_times --save refiner/saved/ --log refiner/logs/ --name times_nll_0.55_50000


# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 500 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size   100 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.55_100
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 300 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size   200 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.55_200
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 200 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size   500 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.55_500
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 100 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size  1000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.55_1000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 50 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size  2000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.55_2000
python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 30 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size  5000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.55_5000
python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 20 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size 10000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.55_10000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 15 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size 20000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.55_20000
# python refine_apprentice.py --refiner unet --lbd 0.55 --delta feature_l1 --eta nll --epochs 10 --optimizer Adam --lr 1e-4 --batch-size 50 --test-batch 1000 --train-size 50000 --test-size 10000 --classifier-path classifier/saved/ --classifier-name ideal_mixall --save refiner/saved/ --log refiner/logs/ --name mixall_nll_0.55_50000
